### ISSUE TITLE
Can't import any new adventures

### ISSUE THREAD

**Issue by theksi** [fryguy1013/pdftofoundry#6] opened 2023-08-09 09:13 UTC
Hello,
Just to report that the import of PFS scenario 1-20 (Lost Legend) immediately failed after import
- FVTT version 11.307
- PF2e version 5.3.1
- Pdf foundry importer version 4.1.1

I have tried to import other files (i.e. 3-01, Fall of plaguestone) with the same result. 

Please find hereunder an extract of the console error message : 

```
foundry.js:5724 Foundry VTT | Rendering Dialog
importer.mjs:1 Uncaught (in promise) _UnknownErrorException {message: 'The `Array.prototype` contains unexpected enumerab…n of `Array`s.\n[Detected 1 package: pdftofoundry]', name: 'UnknownErrorException', details: 'Error: The `Array.prototype` contains unexpected e…s breaking e.g. `for...in` iteration of `Array`s.', stack: 'Error\n    at BaseExceptionClosure (http://localhos…st:30021/modules/pdftofoundry/vendor.mjs:17:52166', libwrapper_skip_package_detection: true}
generateData @ importer.mjs:1
await in generateData (async)
callback @ FoundryGui.mjs:1
await in callback (async)
submit @ foundry.js:65005
_onClickButton @ foundry.js:64933
dispatch @ jquery.min.js:2
y.handle @ jquery.min.js:2
```
__**Workaround**__
- Import in foundry V10 (or V11 with an earlier version of the PF2e system)
- Use Advendture bundler to export the import
- Import the Adventure bundle into the V11 foundry instance

**Comment by fryguy1013** [comment] 2023-08-09 10:31
Dupe of #3

**Closed as completed by fryguy1013** 2023-08-09 10:31 UTC
