### ISSUE TITLE
Can't import Troubles in Otari

### ISSUE THREAD

**Issue by markbruno** [fryguy1013/pdftofoundry#5] opened 2023-08-04 21:05 UTC
Just purchase a copy of the PDF today from Paizo and tried to import it with this module, but it doesn't seem to be importing anything; I don't even get an error message.

I'm running Foundry V11 Build 304, PF2e 5.3.0 and downloaded the latest version of this module.

**Comment by fryguy1013** [comment] 2023-08-14 05:55
Duplicate of #3

**Closed as completed by fryguy1013** 2023-08-14 05:55 UTC
